
Passed arguments:
Namespace(app_mix='./apps_mix/a2a_b/1GiB', node_file='auto', numnodes=8, allocationmode='l', allocationsplit='100', minruns=1, maxruns=3, timeout=300.0, alpha=0.05, beta=0.05, ppn=1, convergeall=False, outformat='csv', runtimeout='+file', seed=1, datapath='./data', extrainfo=None, replace_mix_args=None)

Apps:
0: with arguments:"-msgsize 1073741824 -iter 100 -grty 1", collection flag: True, ending condition: run until finished.

Node allocation:
Processes per node (ppn): 1
0 on 8 nodes:
['nid005370' 'nid005371' 'nid005412' 'nid005413' 'nid005414' 'nid005418'
 'nid005419' 'nid005420']

Schedule:
0.0s: start 0

Preparing took 0.02413s.

Running...
 Run 1:
  0.00102s: started 0
  9.91057s: awaited 0
  9.91059s: encountered an exception in 0
srun: error: nid005413: task 3: Segmentation fault
srun: launch/slurm: _step_signal: Terminating StepId=6652873.68
srun: error: nid005412: task 2: Segmentation fault
srun: error: nid005370: task 0: Segmentation fault
srun: error: nid005371: task 1: Segmentation fault
srun: error: nid005414: task 4: Segmentation fault (core dumped)
srun: error: nid005420: task 7: Terminated
srun: error: nid005418: task 5: Terminated
srun: error: nid005419: task 6: Terminated
srun: Force Terminated StepId=6652873.68

  Data collection took 1e-05s.
  Convergence check took 0.0s.
 Run 2:
  0.00104s: started 0
  7.45153s: awaited 0
  7.45155s: encountered an exception in 0
srun: error: nid005414: task 4: Segmentation fault
srun: launch/slurm: _step_signal: Terminating StepId=6652873.69
srun: error: nid005413: task 3: Segmentation fault
srun: error: nid005412: task 2: Segmentation fault
srun: error: nid005371: task 1: Segmentation fault
srun: error: nid005370: task 0: Segmentation fault
srun: error: nid005419: task 6: Terminated
srun: error: nid005420: task 7: Terminated
srun: error: nid005418: task 5: Terminated
srun: Force Terminated StepId=6652873.69

  Data collection took 1e-05s.
  Convergence check took 0.0s.
 Run 3:
  0.00111s: started 0
  15.13592s: awaited 0
  15.13594s: encountered an exception in 0
srun: error: nid005413: task 3: Segmentation fault
srun: launch/slurm: _step_signal: Terminating StepId=6652873.70
srun: error: nid005412: task 2: Segmentation fault
srun: error: nid005371: task 1: Segmentation fault
srun: error: nid005414: task 4: Segmentation fault
srun: error: nid005370: task 0: Segmentation fault
srun: error: nid005419: task 6: Terminated
srun: error: nid005420: task 7: Terminated
srun: error: nid005418: task 5: Terminated
srun: Force Terminated StepId=6652873.70

  Data collection took 1e-05s.
  Convergence check took 0.0s.
Completed maximum number of runs, terminated after 3 runs taking 32.5 seconds.
